apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agentmeter
resources:
  - namespace.yaml
  - service-accounts.yaml
  - config.yaml
  - migration.yaml
  - workloads.yaml
  - services.yaml
  - ingress.yaml
  - autoscaling.yaml
  - availability.yaml
  - network-policies.yaml
images:
  - name: agentmeter
    newName: ghcr.io/ayan-saiyad/agentmeter
    newTag: latest
