apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - name: http
      port: 4000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
spec:
  selector:
    app.kubernetes.io/name: dashboard
  ports:
    - name: http
      port: 3000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: provider-simulator
spec:
  selector:
    app.kubernetes.io/name: provider-simulator
  ports:
    - name: http
      port: 4100
      targetPort: http
