apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-simulator
